"""empty message

Revision ID: 12ee587c5a67
Revises: 
Create Date: 2022-09-20 22:27:32.598108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ee587c5a67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.String(length=30), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_id')
    )
    op.create_table('youtube_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_link', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('youtube_publish_date', sa.DateTime(), nullable=True),
    sa.Column('is_published_in_tg', sa.Boolean(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_video')
    op.drop_table('youtube_channel')
    # ### end Alembic commands ###
