"""empty message

Revision ID: 85cf260381ab
Revises: 2df1d642b9f6
Create Date: 2022-09-24 00:25:05.491530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85cf260381ab'
down_revision = '2df1d642b9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'date_added')
    # ### end Alembic commands ###
